import { join } from 'path';
import type { EditorAdapter, SyncResult } from '../core/types.js';
import { AUTO_GENERATED_MARKER } from '../core/types.js';
import { findMarkdownFiles, readTextFile, removeFile } from '../utils/file-ops.js';
import { log } from '../utils/logger.js';

export async function cleanupOrphans(
  projectRoot: string,
  adapters: EditorAdapter[],
  result: SyncResult,
): Promise<string[]> {
  const removed: string[] = [];

  for (const adapter of adapters) {
    const dirs = [
      adapter.directories.rules,
      adapter.directories.skills,
      adapter.directories.workflows,
    ].filter(Boolean) as string[];

    const uniqueDirs = [...new Set(dirs)];

    for (const dir of uniqueDirs) {
      const fullDir = join(projectRoot, dir);
      const files = await findMarkdownFiles(fullDir, fullDir);

      for (const file of files) {
        // Only remove files that were auto-generated by ai-toolkit
        if (file.content.includes(AUTO_GENERATED_MARKER)) {
          // Check if this file is in the current sync result
          const fullPath = join(fullDir, file.relativePath);
          if (!result.synced.includes(fullPath)) {
            const success = await removeFile(fullPath);
            if (success) {
              const relativePath = join(dir, file.relativePath);
              log.removed(relativePath);
              removed.push(relativePath);
            }
          }
        }
      }
    }
  }

  return removed;
}
